# Levantar el ambiente: docker-compose up
# Para reiniciar todo el ambiente: docker-compose down -v
# este comando es para cuando hay bugs de conexion
version: '3.3'
services:
  mysql_db_vendure:
    container_name: mysql_db_vendure
    image: mysql:8.0.29
    restart: always
    environment:
      # Nombre de la base de datos
      MYSQL_DATABASE: 'development'
      # Usuario de la base de datos
      MYSQL_USER: 'development'
      # Password de la base de datos
      MYSQL_PASSWORD: 'development'
      # Password del root
      MYSQL_ROOT_PASSWORD: 'development'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '30510:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - mysql-volume:/var/lib/mysql
  redis_db_vendure:
    container_name: redis_db_vendure
    image: redis:latest
    restart: always
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '30511:6379'
    expose:
      # Opens port 6379 on the container
      - '6379'
    volumes:
      - redis-volume:/data
# Names our volume
volumes:
  mysql-volume:
  redis-volume:

